---
title: "Introduction to massFlowR package"
output:
  BiocStyle::html_document:
    toc_float: true
vignette: >
  %\VignetteIndexEntry{Put the title of your vignette here}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
  %\VignettePackage{massFlowR}
  %\VignetteKeywords{mass spectrometry, metabolomics}
---

**Package**: [massFlowR](https://github.com/lauzikaite/massFlowR)<br />
**Authors**: Elzbieta Lauzikaite<br />
**Modified**: `r file.info("massFloWR.Rmd")$mtime`<br />
**Compiled**: `r date()`

```{r  biocstyle, include = FALSE, echo = FALSE, results = "asis" }
BiocStyle::markdown() 
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Overview

This documents provides an overview of the LC-MS data pre-processing with `massFlowR`.

`massFlowR` annotates and aligns structurally-related spectral peaks across LC-MS experiment samples. Its pipeline consists of three stages:

## Individual samples processing

Each LC-MS file in the experiment is processed independently.
 
* Chromatographic peak detection is enabled by the *centWave* algorithm from `xcms` package.

* Grouping of chromatographic peaks originating from the same chemical compound into structurally-related units is implemented (see [Peak Grouping](#peak-grouping)).
    
## Alignment

To align peaks across all samples in the LC-MS experiment, a peak group alignment algorithm, which compares the overall similarity of peak groups is implemented (see [Peak alignment](#peak-alignment)). If in-house chemical reference database is available, peaks are annotated during sample alignment (see [Peak annotation](#peak-annotation)).
Sample alignment can be performed in real-time during raw LC-MS file acquisition, mzML conversion and initial processing.

## Alignment validation and peak filling

*(to be implemented)*

Once samples are aligned, the obtained peak groups are validated. Intensity values for each peak in a group are correlated across all samples. Correlation estimates are then used to build networks of peaks, that behave similarly across all samples. Peaks exhibiting a different pattern in their intensities are put into a new peak-group. 

Finally, for samples, in which a peak from a validated peak-group was not detected, peak-filling is performed. Intensity data is obtained for each missing peak using original LC-MS files. In contrast to `xcms` package, *mz* and *rt* values for intensity integration are estimated for each sample separetely. *mz* and *rt* values are taken from two surrounding samples, in which the peak-of-interest was present, and extrapolated. 

# Data import

LC/MS data in mzML format import is supported. Data import is implemented via `Biocpkg(“mzR”)` package. 

# Peak grouping

# Peak annotation

# Peak alignment
