#' Chemical reference database template.
#'
#' @slot filepath A \code{character} specifying path to database csv file.
#'
#' @description \code{massFlowDB} class encapsulates information provided in the chemical reference database.
#' Database contains all of the detected peaks for every chemical in the database. Peaks must be grouped into spectra using \code{pickPEAKS()} function prior to building of the \code{massFlowDB} class object.
#' The final database file is a single csv file, which must contain columns: "peakid", "mz", "rt", "into", "peakgr", "chemid", "dbid", "dbname".
#' Database will be used to initialise \code{massFlowTemplate} class object.
#' Database "peakid" and "peakgr" values will retain unmodified in the template, while every sample in the study will be aligned with them.
#'
#' @slot db A \code{data.frame} containing database template. Template must contain
#' @export
#'
setClass("massFlowDB",
         slots = c(
           filepath = "character",
           db = "data.frame"
         ))


#' Class massFlowTemplate, a class for sample alignment and annotation
#'
#' @description This class enables the alignment and annotation of LC-MS samples.
#' It takes files containing groups of structurally related peaks, generated by \code{groupPEAKS} function, and aligns them in their original sample acquisition order.
#' It validates peak groups obtained during alignment by correlating peak intensities in all samples.
#' Finally, it fills in missing peak intensity values using raw data.
#'
#' @slot filepath A \code{character} specifying the absolute path to a \code{csv} file with study sample names and their acquisition (run) order.
#' @slot db_filepath A \code{character} specifying the absolute path to the database \code{csv} file (if was used in the template built).
#' @slot samples A \code{data.frame} storing study sample names and their acquisition order.
#' @slot tmp A \code{data.frame} storing sample alignment and annotation template.
#' @slot data A \code{list} containg annotated and aligned peak tables for the already processed samples.
#' @slot params A \code{list} containg alignment and annotation parameters.
#'
#' @details \code{massFlowTemplate} object stores sample alignment and annotation data.
#'
#' Slot \code{tmp} is the template, listing information for every detected peak, such as the \emph{mz}, \emph{rt}, \emph{into} values, the assigned peak-group, as well as chemical identifications (if any).
#' Template is initiated using the first datafile in the study and the chemical reference database (\code{massFlowDB} object), if available.
#' To initiate template built, function \code{buildTMP} must be called, providing a "filepath" to the csv file with the details on the study samples.
#'
#' Template is updated with every round of sample alignment. Alignment results are stored in slot \code{data} for each sample separately.
#'
#' @export
#'
setClass("massFlowTemplate",
         slots = c(
           filepath = "character",
           db_filepath = "character",
           samples = "data.frame",
           tmp = "data.frame",
           data = "list",
           params = "list"))
