#' @aliases massFlowDB
#'
#' @title Chemical reference database template
#'
#' @description \code{massFlowDB} class encapsulates information provided in the chemical reference database.
#'
#' @details Chemical reference database file lists peaks \code{centWave}-detected in the reference LC-MS datafiles.
#' The database file is a single csv file, which must contain columns: "peakid", "mz", "rt", "into", "peakgr", "chemid", "dbid", "dbname".
#'
#' To initialise \code{massFlowDB} object, a constructor function \code{\link{buildDB}} mus be used.
#'
#' @slot filepath \code{character} specifying path to database csv file.
#' @slot db \code{data.frame} containing database template.
#'
#' @rdname massFlowDB-class
#'
#' @seealso \code{\link{buildDB}}
#'
#' @export
#'
setClass("massFlowDB",
         slots = c(filepath = "character",
                   db = "data.frame"))


#' @aliases massFlowTemplate
#'
#' @title massFlowTemplate, a class for sample alignment and annotation
#'
#' @description This class enables the alignment and annotation of LC-MS samples.
#' It takes files containing groups of structurally related peaks, generated by \code{\link{groupPEAKS}} function, and aligns them in their original sample acquisition order.
#' It validates peak groups obtained during alignment by correlating peak intensities in all samples.
#' Finally, it fills in missing peak intensity values using raw data.
#'
#' @details \code{massFlowTemplate} object stores sample alignment and annotation data.
#'
#' \itemize{
#' \item Slot @@tmp is the template, listing information for every detected peak, such as the \emph{m/z}, \emph{rt}, \emph{into} values, the assigned peak-group, as well as chemical identifications (if any).
#' \item Template is first built using the first datafile in the study, and, if available, the chemical reference database (\code{\link{massFlowDB}} object).
#' To initiate template built, constructor function \code{\link{buildTMP}} must be called, providing a "filepath" to the csv file with the details on the study samples.
#' \item Template is updated with every round of sample alignment.
#' Alignment results are stored in slot @@data for each sample separately.
#' }
#'
#' @slot filepath \code{character} specifying the absolute path to a \code{csv} file with study sample names and their acquisition (run) order.
#' @slot db_filepath \code{character} specifying the absolute path to the database \code{csv} file (if was used in the template built).
#' @slot samples \code{data.frame} storing study sample names and their acquisition order.
#' @slot tmp \code{data.frame} storing sample alignment and annotation template.
#' @slot data \code{list} containg annotated and aligned peak tables for the already processed samples.
#' @slot params \code{list} containg alignment and annotation parameters.
#'
#' @seealso \code{\link{buildTMP}}, \code{\link{alignPEAKS}}
#'
#' @rdname massFlowTemplate-class
#'
#' @export
#'
setClass(
  "massFlowTemplate",
  slots = c(
    filepath = "character",
    db_filepath = "character",
    samples = "data.frame",
    tmp = "data.frame",
    data = "list",
    params = "list"
  )
)
