setGeneric("filepath", function(object) standardGeneric("filepath"))
setGeneric("peaksVALIDATED", function(object) standardGeneric("peaksVALIDATED"))
setGeneric("chemicals", function(object) standardGeneric("chemicals"))
setGeneric("alignPEAKS", function(object, out_dir, write_int = TRUE, ...) standardGeneric("alignPEAKS"))
setGeneric("checkNEXT", function(object) standardGeneric("checkNEXT"))
setGeneric("validPEAKS", function(object, out_dir, ...) standardGeneric("validPEAKS"))
setGeneric("fillPEAKS", function(object, fill_value = "into", out_dir, ...) standardGeneric("fillPEAKS"))
setGeneric("annotatePEAKS", function(object, database, out_dir, ...) standardGeneric("annotatePEAKS"))
